version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:14.0-alpine
    ports:
      - 6001:${POSTGRES_PORT}
    volumes:
      - ./pg:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  # backend:
  #   container_name: pattern_bd
  #   build:
  #     context: ../pattern_bd
  #   depends_on:
  #     - db
  #   restart: unless-stopped
  #   ports:
  #     - '${PORT}:3001'
  #   environment:
  #     - PORT=${PORT}
  #     - HOST=${HOST}
  #     - POSTGRES_CONNECTION=${POSTGRES_CONNECTION}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_PORT=${POSTGRES_PORT}
  #     - POSTGRES_HOST=${POSTGRES_HOST}